version: "3.9"

services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync+restart
          path: ../server.js
          target: /server.js
        - action: sync
          path: ../
          target: /