name: Update build.txt

on:
  push:
      branches:
        - main

jobs:
  update-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Update build.txt with the latest commit hash
        run: |
          git rev-parse HEAD > public/build.txt
      
      - name: Commit and push build.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/build.txt
          git commit -m "chore: update build.txt with latest commit"
          git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}